### ISSUE TITLE
Error not displayed correctly

### ISSUE THREAD

**Issue by schiesbn** [owncloud/files_texteditor#126]
If a exception occurs while loading a file we don't display a error message, instead we see a spinner forever. The texteditor in oC8.1 showed a popup with a error message.

Internally the error handling is the same, compare
https://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L112
and
https://github.com/owncloud/files_texteditor/blob/stable8.1/controller/filehandlingcontroller.php#L106

But for some reasons the response is no longer handled correctly on master.

**Comment by tomneedham** [comment]
@schiesbn Am I right in thinking this is fixed now? Can't remember the conclusion of the discussion in the other ticket https://github.com/owncloud/files_texteditor/pull/125/files and https://github.com/owncloud/files_texteditor/pull/97

**Comment by schiesbn** [comment]
no it is not fixed. The pull request you mention make sure that the correct error message is returned from the server but the new text editor doesn't show the error message, instead you see a spinner forever. The old texteditor showed the error in a pop-up dialog. I assume that the client side (javascript) handling of the failure get lost during the switch to the the new way the text editor is displayed.

**Comment by tomneedham** [comment]
Ok I'll take a look

**Comment by PVince81** [comment]
@tomneedham can you have a look ? Does it still happen in 8.2.1 ?

**Comment by tomneedham** [comment]
8.2.1 I get this: 
<img width="412" alt="screen shot 2015-12-04 at 11 59 32" src="https://cloud.githubusercontent.com/assets/660805/11589209/8a34e646-9a7e-11e5-8a53-8059f89c73e9.png"> if I throw an exception in the load file controller.

**Comment by tomneedham** [comment]
As handled here: https://github.com/owncloud/files_texteditor/blob/stable8.2/js/editor.js#L320.

**Comment by tomneedham** [comment]
@schiesbn ?

**Comment by nickvergessen** [comment]
Would be nice to not kill the actual message, if one is returned?

**Comment by nickvergessen** [comment]
I see you already check for OC\HintException manually.

Storages also throw some known ones (locked, storage-not-available, forbidden (firewall)), identifying them with a correct message would be very nice
